<?php
declare(strict_types=1);

namespace OCA\TeamHub\Controller;

use OCA\TeamHub\AppInfo\Application;
use OCA\TeamHub\Service\TeamImportService;
use OCP\AppFramework\Controller;
use OCP\AppFramework\Http;
use OCP\AppFramework\Http\Attribute\AuthorizedAdminSetting;
use OCP\AppFramework\Http\Attribute\NoCSRFRequired;
use OCP\AppFramework\Http\DataDownloadResponse;
use OCP\AppFramework\Http\JSONResponse;
use OCP\IRequest;
use Psr\Log\LoggerInterface;

/**
 * Bulk team import — NC-admin only (v4.6.6).
 *
 * Authorisation is deliberately doubled, copying {@see MaintenanceController}
 * verbatim: `#[AuthorizedAdminSetting]` on **every** method, plus
 * `TeamImportService::requireNcAdmin()` inside every service entry point. This
 * endpoint creates teams and transfers their ownership; "the frontend won't
 * call it" is not a boundary.
 *
 * There is no `#[NoAdminRequired]` anywhere in this file, and there must never
 * be one — a single occurrence would open bulk team creation to every account
 * on the instance.
 *
 * `#[NoCSRFRequired]` appears only on the three read-only GETs, matching
 * MaintenanceController's convention of marking its GETs and nothing else. The
 * template download needs it because the browser fetches that URL directly,
 * without an axios-supplied token. Every state-changing verb here — validate,
 * start, process, delete — stays CSRF-protected.
 */
class TeamImportController extends Controller {

    public function __construct(
        string $appName,
        IRequest $request,
        private TeamImportService $importService,
        private LoggerInterface   $logger,
    ) {
        parent::__construct($appName, $request);
    }

    // -------------------------------------------------------------------------
    // Sample CSV
    // -------------------------------------------------------------------------

    /**
     * GET /api/v1/admin/import/teams/template
     *
     * The sample CSV, generated by the same class that parses uploads so the
     * two can never drift.
     */
    #[AuthorizedAdminSetting(settings: \OCA\TeamHub\Settings\AdminSettings::class)]
    #[NoCSRFRequired]
    public function template(): DataDownloadResponse|JSONResponse {
        try {
            $this->importService->requireNcAdmin();

            return new DataDownloadResponse(
                $this->importService->sampleCsv(),
                'teamhub-team-import-template.csv',
                'text/csv; charset=utf-8',
            );
        } catch (\Throwable $e) {
            return new JSONResponse(['error' => 'Forbidden'], Http::STATUS_FORBIDDEN);
        }
    }

    // -------------------------------------------------------------------------
    // Validate (dry run)
    // -------------------------------------------------------------------------

    /**
     * POST /api/v1/admin/import/teams/validate
     *
     * Multipart upload, file field `file`. Parses, normalises and persists the
     * run, then returns its preview. Nothing is created until `start()`.
     */
    #[AuthorizedAdminSetting(settings: \OCA\TeamHub\Settings\AdminSettings::class)]
    public function validate(): JSONResponse {
        $file = $this->request->getUploadedFile('file');

        if (empty($file) || ($file['error'] ?? UPLOAD_ERR_NO_FILE) !== UPLOAD_ERR_OK) {
            return new JSONResponse(
                ['error' => 'No file uploaded or upload error: ' . ($file['error'] ?? UPLOAD_ERR_NO_FILE)],
                Http::STATUS_BAD_REQUEST,
            );
        }

        // Size guard before reading anything into memory — same order as
        // TeamImageController::upload(), for the same reason.
        if (($file['size'] ?? 0) > TeamImportService::MAX_UPLOAD_BYTES) {
            return new JSONResponse(
                ['error' => 'File is too large. Maximum size is 2 MB.'],
                Http::STATUS_BAD_REQUEST,
            );
        }

        $tmpPath = $file['tmp_name'] ?? '';
        if (!$tmpPath || !is_readable($tmpPath)) {
            return new JSONResponse(['error' => 'Uploaded file is not readable'], Http::STATUS_BAD_REQUEST);
        }

        $raw = file_get_contents($tmpPath);
        if ($raw === false) {
            return new JSONResponse(['error' => 'Failed to read uploaded file'], Http::STATUS_INTERNAL_SERVER_ERROR);
        }

        // The client-supplied name is display-only. Strip any path segment so a
        // crafted `../` name cannot reach anything: it is stored and rendered,
        // never resolved as a path, and basename() keeps that true by
        // construction rather than by everyone downstream remembering.
        $filename = basename((string)($file['name'] ?? 'import.csv'));

        try {
            return new JSONResponse($this->importService->validate($raw, $filename));
        } catch (\InvalidArgumentException $e) {
            return new JSONResponse(['error' => $e->getMessage()], Http::STATUS_BAD_REQUEST);
        } catch (\RuntimeException $e) {
            return new JSONResponse(['error' => $e->getMessage()], Http::STATUS_FORBIDDEN);
        } catch (\Throwable $e) {
            $this->logger->error('[TeamHub][TeamImportController] validate failed', [
                'error' => $e->getMessage(), 'app' => Application::APP_ID,
            ]);

            return new JSONResponse(['error' => 'Could not read the uploaded file.'], Http::STATUS_INTERNAL_SERVER_ERROR);
        }
    }

    // -------------------------------------------------------------------------
    // Run control
    // -------------------------------------------------------------------------

    /**
     * POST /api/v1/admin/import/teams/{id}/start
     *
     * Confirm a validated run. Idempotent — a second call reports the run's
     * current state rather than restarting it.
     */
    #[AuthorizedAdminSetting(settings: \OCA\TeamHub\Settings\AdminSettings::class)]
    public function start(int $id): JSONResponse {
        try {
            return new JSONResponse($this->importService->start($id));
        } catch (\RuntimeException $e) {
            return $this->runtimeResponse($e);
        } catch (\Throwable $e) {
            return $this->failure('start', $id, $e);
        }
    }

    /**
     * POST /api/v1/admin/import/teams/{id}/process
     *
     * Provision the next chunk and return progress. The admin panel calls this
     * in a loop until the run reports `completed`.
     */
    #[AuthorizedAdminSetting(settings: \OCA\TeamHub\Settings\AdminSettings::class)]
    public function process(int $id, int $limit = TeamImportService::DEFAULT_CHUNK): JSONResponse {
        try {
            return new JSONResponse($this->importService->processNextChunk($id, $limit));
        } catch (\RuntimeException $e) {
            return $this->runtimeResponse($e);
        } catch (\Throwable $e) {
            return $this->failure('process', $id, $e);
        }
    }

    /**
     * GET /api/v1/admin/import/teams/{id}
     *
     * Polling endpoint — read-only, so safe to mark CSRF-exempt.
     */
    #[AuthorizedAdminSetting(settings: \OCA\TeamHub\Settings\AdminSettings::class)]
    #[NoCSRFRequired]
    public function show(int $id): JSONResponse {
        try {
            return new JSONResponse($this->importService->getImport($id));
        } catch (\RuntimeException $e) {
            return $this->runtimeResponse($e);
        } catch (\Throwable $e) {
            return $this->failure('show', $id, $e);
        }
    }

    /**
     * DELETE /api/v1/admin/import/teams/{id}
     *
     * Discards a validated run outright; cancels one already in flight, leaving
     * the teams it has already created alone.
     */
    #[AuthorizedAdminSetting(settings: \OCA\TeamHub\Settings\AdminSettings::class)]
    public function destroy(int $id): JSONResponse {
        try {
            return new JSONResponse($this->importService->discard($id));
        } catch (\RuntimeException $e) {
            return $this->runtimeResponse($e);
        } catch (\Throwable $e) {
            return $this->failure('destroy', $id, $e);
        }
    }

    /**
     * GET /api/v1/admin/import/teams
     *
     * Recent runs, newest first.
     */
    #[AuthorizedAdminSetting(settings: \OCA\TeamHub\Settings\AdminSettings::class)]
    #[NoCSRFRequired]
    public function index(int $limit = 10): JSONResponse {
        try {
            return new JSONResponse(['imports' => $this->importService->listRecent($limit)]);
        } catch (\RuntimeException $e) {
            return $this->runtimeResponse($e);
        } catch (\Throwable $e) {
            return $this->failure('index', 0, $e);
        }
    }

    // -------------------------------------------------------------------------
    // Error mapping
    // -------------------------------------------------------------------------

    /**
     * Map the service's two RuntimeException cases onto the right status.
     *
     * The service throws RuntimeException for both "not an admin" and "no such
     * import"; answering either with a 500 would be the same status-code bug
     * `TeamController` is already carrying (HANDOFF.md, open issues).
     */
    private function runtimeResponse(\RuntimeException $e): JSONResponse {
        $message = $e->getMessage();
        if (str_contains($message, 'not found')) {
            return new JSONResponse(['error' => 'Import not found'], Http::STATUS_NOT_FOUND);
        }

        return new JSONResponse(['error' => 'Forbidden'], Http::STATUS_FORBIDDEN);
    }

    /**
     * Log the detail, return a generic message. The exception text can name
     * internal services and uids; the admin panel does not need it and the
     * response should not carry it.
     */
    private function failure(string $action, int $importId, \Throwable $e): JSONResponse {
        $this->logger->error('[TeamHub][TeamImportController] ' . $action . ' failed', [
            'importId' => $importId,
            'error'    => $e->getMessage(),
            'app'      => Application::APP_ID,
        ]);

        return new JSONResponse(
            ['error' => 'The import could not be processed. Check the Nextcloud log for details.'],
            Http::STATUS_INTERNAL_SERVER_ERROR,
        );
    }
}
