name: Publish to Nextcloud App Store

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    # Geeft de workflow toestemming om bestanden te uploaden naar de release
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP and Build JS
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Build App
        run: |
          npm install
          npm run build
          # Verwijder ballast
          rm -rf node_modules .git .github

      - name: Create App Folder and Tarball
        run: |
          mkdir teamhub
          find . -maxdepth 1 ! -name 'teamhub' ! -name '.' ! -name '..' -exec mv {} teamhub/ \;
          tar -czf teamhub.tar.gz teamhub/

      - name: Upload Tarball to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: teamhub.tar.gz
          # Zorg dat we de exacte tag gebruiken
          tag_name: ${{ github.event.release.tag_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Register in Nextcloud App Store
        uses: R0Wi/nextcloud-appstore-push-action@v1.0.1
        with:
          app_name: teamhub
          app_private_key: ${{ secrets.NEXTCLOUD_KEY }}
          appstore_token: ${{ secrets.NEXTCLOUD_TOKEN }}
          download_url: https://github.com/${{ github.repository }}/releases/download/${{ github.event.release.tag_name }}/teamhub.tar.gz